export type Costume = {
  id: string;
  name: string;
  thumbnail: string;
  image: string;
  author: string;
  booth: string;
  comment: string;
};

export const costumes: Costume[] = [
  {
    id: "DreamyStep",
    name: "Dreamy Step",
    thumbnail: "thumbnails/DreamyStep.png",
    image: "images/DreamyStep.png",
    author: "寺井カントリー",
    booth: "https://booth.pm/ja/items/5420885",
    comment: "いつも標準で使っているお洋服。メガネバージョンとかもあります。",
  },
  {
    id: "巫桜",
    name: "巫桜",
    thumbnail: "thumbnails/巫桜.png",
    image: "images/巫桜.png",
    author: "asapidock",
    booth: "https://booth.pm/ja/items/5646504",
    comment: "FF10配信でこういう感じの和服がほしい！っていうのを探したら見つかったまさにいい感じの巫女服。それだけじゃなくて質も良くて気に入ってます。",
  },
  {
    id: "星宮仕えの天使さん",
    name: "星宮仕えの天使さん",
    thumbnail: "thumbnails/星宮仕えの天使さん.png",
    image: "images/星宮仕えの天使さん.png",
    author: "みさくらやさん",
    booth: "https://booth.pm/ja/items/5646504",
    comment: "かわいい！",
  },
  {
    id: "星術科制服",
    name: "星術科制服",
    thumbnail: "thumbnails/星術科制服.png",
    image: "images/星術科制服.png",
    author: "みさくらやさん",
    booth: "https://booth.pm/ja/items/4702665",
    comment: "しばしばMicrosoft Flight Simulatorで飛行機を飛ばすときにお借りしているお洋服。機長っぽくない？",
  },
  {
    id: "跋星の白装v2",
    name: "跋星の白装v2",
    thumbnail: "thumbnails/跋星の白装v2.png",
    image: "images/跋星の白装v2.png",
    author: "みさくらやさん",
    booth: "https://booth.pm/ja/items/3622367",
    comment: "コートの星がかわいいです✨️",
  },
  {
    id: "天溢の蒼衣v2",
    name: "天溢の蒼衣v2",
    thumbnail: "thumbnails/天溢の蒼衣v2.png",
    image: "images/天溢の蒼衣v2.png",
    author: "みさくらやさん",
    booth: "https://booth.pm/ja/items/3622367",
    comment: "",
  },
  {
    id: "KEITAMARUYAMA3D着物2023",
    name: "KEITAMARUYAMA3D着物2023",
    thumbnail: "thumbnails/KEITAMARUYAMA3D着物2023.png",
    image: "images/KEITAMARUYAMA3D着物2023.png",
    author: "©️KEITAMARUYAMA",
    booth: "https://booth.pm/ja/items/5378258",
    comment: "",
  },
  {
    id: "LilyBellReOrder",
    name: "Lily Bell - ReOrder",
    thumbnail: "thumbnails/LilyBellReOrder.png",
    image: "images/LilyBellReOrder.png",
    author: "©Sweet Serenade",
    booth: "https://booth.pm/ja/items/5691110",
    comment: "とても布の表現のできが良いかわいいメイドさんです✨️",
  },
  {
    id: "Prelude",
    name: "Prelude",
    thumbnail: "thumbnails/Prelude.png",
    image: "images/Prelude.png",
    author: "©Sweet Serenade",
    booth: "https://booth.pm/ja/items/5134409",
    comment: "変身ギミックのついているお洋服です✨️️",
  },
  {
    id: "Prelude_Transformed",
    name: "Prelude(Transformed)",
    thumbnail: "thumbnails/Prelude_Transformed.png",
    image: "images/Prelude_Transformed.png",
    author: "©Sweet Serenade",
    booth: "https://booth.pm/ja/items/5134409",
    comment: "Preludeの変身ギミックをONにした状態です✨️",
  },
  {
    id: "LittleQueen",
    name: "LittleQueen",
    thumbnail: "thumbnails/LittleQueen.png",
    image: "images/LittleQueen.png",
    author: "choco*shop",
    booth: "https://booth.pm/ja/items/6178156",
    comment: "質感の素敵な衣装です～",
  },
  {
    id: "NightInYoshiwara",
    name: "ナイト・イン・ヨシワラ",
    thumbnail: "thumbnails/NightInYoshiwara.png",
    image: "images/NightInYoshiwara.png",
    author: "©Vagrant",
    booth: "https://booth.pm/ja/items/",
    comment: "とてもセクシーなアバター衣装です✨️",
  },
  {
    id: "SailorLoliRe",
    name: "Re:セーラーロリ",
    thumbnail: "thumbnails/SailorLoliRe.png",
    image: "images/SailorLoliRe.png",
    author: "かぷちや",
    booth: "https://booth.pm/ja/items/4871296",
    comment: "",
  },
  {
    id: "SecretGarden",
    name: "SecretGarden",
    thumbnail: "thumbnails/SecretGarden.png",
    image: "images/SecretGarden.png",
    author: "©ottotto/POTATOTO",
    booth: "https://booth.pm/ja/items/6169513",
    comment: "",
  },
  {
    id: "SnowBell",
    name: "スノーベル",
    thumbnail: "thumbnails/SnowBell.png",
    image: "images/SnowBell.png",
    author: "Radiant-Iseo",
    booth: "https://booth.pm/ja/items/6370137",
    comment: "",
  },
  {
    id: "SnowSpirit",
    name: "Snow Spirit / スノウスピリット",
    thumbnail: "thumbnails/SnowSpirit.png",
    image: "images/SnowSpirit.png",
    author: "©Riisya Sweets",
    booth: "https://booth.pm/ja/items/6403595",
    comment: "",
  },
  {
    id: "お姉さんコーデ",
    name: "お姉さんコーデ",
    thumbnail: "thumbnails/お姉さんコーデ.png",
    image: "images/お姉さんコーデ.png",
    author: "北極狐",
    booth: "https://booth.pm/ja/items/6274337",
    comment: "",
  },
  {
    id: "ルッカ風",
    name: "ルッカ風",
    thumbnail: "thumbnails/ルッカ風.png",
    image: "images/ルッカ風.png",
    author: "cherry neru",
    booth: "https://booth.pm/ja/items/5628717",
    comment: "この衣装は上記以外にも複数の衣装の組み合わせで実現しています。スカーフ部分はReさいくるしょっぷさまのRe-scarf-, ヘルメットは部屋の四隅さまのOPSCORE, バッグは天江製作所さまのウエストバッグを使用させていただきました。",
  },
];
